### ISSUE TITLE
Unable to publish data using the DKG client library v5 using multiple DKG client nodes

### ISSUE THREAD

**Issue by ltfschoen** [OriginTrail/dkg-client#11]
I was already running the ot-node using v5 with one (1) DC node and two (2) DH nodes running.
I followed the DKG client library v5 steps here to publish using simplePrepare https://docs.origintrail.io/developers/using-dkg-v5/devsinstall#publishing-data-using-the-dkg-client-library, however it gives error `Error: Failed to choose holders. Not enough DHs submitted`, which based on review of the ot-node codebase appears to be because I need to have at least three (3) DH nodes running to provide sufficient verified replications. 

Log of running DKG Client library v5
			```
			git clone https://github.com/OriginTrail/dkg-client
			cd dkg-client
			nvm use v9.11.2
			npm install
			node
			```

			```
			> var OT_NODE_HOSTNAME = "0.0.0.0";
			> var OT_NODE_PORT = "8900";
			> var DKGClient = require('/Users/cuttlefish/code/github/dkg-client/index.js');
			> DKGClient
			[Function: DKGClient]
			> var dkg = new DKGClient();
			> dkg
			DKGClient {}
			> dkg.init(OT_NODE_HOSTNAME,OT_NODE_PORT,false);
			> const simpleDataset = dkg.simplePrepare({
			...     identifier_type: 'YOUR_TYPE', // e.g. DID, SGTIN, URL etc
			...     identifier_value: '12345',
			...     properties:{
			.....         hello: 'world'
			.....     }
			... });
			> simpleDataset
			'\n{\n  "@graph": [\n    {\n      "@id": "12345",\n      "@type": "otObject",\n      "identifiers": [\n        {\n          "@type": "YOUR_TYPE",\n          "@value": "12345"\n        }\n      ],\n      "properties": {"hello":"world"},\n      "relations": []\n    }\n  ]\n}\n'
			> const simpleDataset = dkg.simplePrepare({
			...     identifier_type: 'YOUR_TYPE', // e.g. DID, SGTIN, URL etc
			...     identifier_value: '12345',
			...     properties:{
			.....         hello: 'world'
			.....     }
			... 
			> // publishing a dataset
			> dkg.publish(simpleDataset).then((publish_result)=>{
			...     console.log(publish_result);
			... });
			Sending import request.
			Promise {
			  <pending>,
			  domain: 
			   Domain {
			     domain: null,
			     _events: 
			      { removeListener: [Function: updateExceptionCapture],
			        newListener: [Function: updateExceptionCapture],
			        error: [Function: debugDomainError] },
			     _eventsCount: 3,
			     _maxListeners: undefined,
			     members: [] } }
			> Import result status: COMPLETED
			Sending replication request.
			Replication result status: PENDING
                      ...
			Replication result status: PENDING
			Replication result status: FAILED
			(node:48126) UnhandledPromiseRejectionWarning: Error: Replication failed. Reason: undefined.
			    at DKGClient._getReplicationResult (/Users/cuttlefish/code/github/dkg-client/index.js:320:19)
			    at <anonymous>
			    at process._tickCallback (internal/process/next_tick.js:182:7)
			(node:48126) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
			(node:48126) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
			```

Logs from the OT-node v5
			```
			2022-10-24T00:09:24.827Z - api - POST: Replicate request received.
			2022-10-24T00:09:24.869Z - trace - [stargazer] Using default trac price in base currency from configuration: 0.00005
			2022-10-24T00:09:24.870Z - trace - [stargazer] Using default gas price from configuration: 20000000000
			2022-10-24T00:09:24.870Z - trace - Calculated offer price for data size: 0.002111MB, and holding time: 0.006944444444444444 days, PRICE: 120016244229744740000[mTRAC]
			2022-10-24T00:09:24.877Z - trace - [stargazer] Get profile by identity 0x2fa6d32e314aab43a58999d6f5532a15418da153
			2022-10-24T00:09:24.927Z - trace - [stargazer] Get minimum stake from blockchain
			2022-10-24T00:09:24.958Z - info - Exporting dataset: 0x9389afa0dc8b3a177461b577162085acc740f627bfbdb70488041e823b8080d5. For internal offer id: a5848007-8fcf-42b1-ae52-ec3c27063ad5.
			2022-10-24T00:09:24.977Z - info - Preparing data for offer with internal id: a5848007-8fcf-42b1-ae52-ec3c27063ad5, started.
			(node:48552) Warning: N-API is an experimental feature and could change at any time.
			2022-10-24T00:09:37.017Z - info - Preparing data for offer with internal id: a5848007-8fcf-42b1-ae52-ec3c27063ad5, completed successfully.
			2022-10-24T00:09:37.112Z - trace - [stargazer] Using default gas price from configuration: 20000000000
			2022-10-24T00:09:37.113Z - trace - [stargazer] createOffer (0x2fa6d32e314aab43a58999d6f5532a15418da153, 0x9389afa0dc8b3a177461b577162085acc740f627bfbdb70488041e823b8080d5, 0x9f9c70de04049a71ef0edb819c1c588d2f938cce1d53dca174f4f9c614af24d4, 0x106d1e85c1558430faba36255b066b436ed45fbd4ddce05a803b99cec60af448, 0x81923da63de846527eb78635643dc13ae9a2c6a27b679c8636e0b96ec3cc1b9a, 0x41839f9f2ae6f4fb01c51ac3e8ac2ac1c9505d8e6e34d5964d7190555b390e3b, 0x781e64952478359bd10b79ab69d42bea189834be, 10, 120016244229744740000, 2111, 1)
			2022-10-24T00:09:37.135Z - trace - Sending transaction to blockchain, nonce 60, balance is 999999999998456438980000000000
			2022-10-24T00:09:37.520Z - important - Offer with internal ID a5848007-8fcf-42b1-ae52-ec3c27063ad5 for data set 0x9389afa0dc8b3a177461b577162085acc740f627bfbdb70488041e823b8080d5 written to blockchain stargazer. Waiting for DHs...
			2022-10-24T00:09:57.813Z - trace - Offer successfully started for data set 0x9389afa0dc8b3a177461b577162085acc740f627bfbdb70488041e823b8080d5 on blockchain stargazer. Offer ID 0x77fad6d671c54ea552aae951edc4f3ae573f8450f1a2ac055af1a927ce86b6bb. Internal offer ID a5848007-8fcf-42b1-ae52-ec3c27063ad5.
			2022-10-24T00:10:32.734Z - info - Received replication request for offer_id 0x77fad6d671c54ea552aae951edc4f3ae573f8450f1a2ac055af1a927ce86b6bb from node 85b7d412ab88d04136568e7618cfeb0ce4e9c94b.
			2022-10-24T00:10:32.742Z - info - Sending replication request acknowledgement for offer_id 0x77fad6d671c54ea552aae951edc4f3ae573f8450f1a2ac055af1a927ce86b6bb to node 85b7d412ab88d04136568e7618cfeb0ce4e9c94b.
			2022-10-24T00:10:37.719Z - info - Received replication request for offer_id 0x77fad6d671c54ea552aae951edc4f3ae573f8450f1a2ac055af1a927ce86b6bb from node 4ab6cd2fb8330cea9397915ef1adaa5e4290a7a3.
			2022-10-24T00:10:37.728Z - info - Sending replication request acknowledgement for offer_id 0x77fad6d671c54ea552aae951edc4f3ae573f8450f1a2ac055af1a927ce86b6bb to node 4ab6cd2fb8330cea9397915ef1adaa5e4290a7a3.
			2022-10-24T00:10:53.524Z - trace - Loaded replication from file for offer internal ID a5848007-8fcf-42b1-ae52-ec3c27063ad5 and color red
			2022-10-24T00:10:53.757Z - info - Successfully sent replication data for offer_id 0x77fad6d671c54ea552aae951edc4f3ae573f8450f1a2ac055af1a927ce86b6bb to node 4ab6cd2fb8330cea9397915ef1adaa5e4290a7a3.
			2022-10-24T00:10:54.141Z - trace - [stargazer] Reading HOLDING_CONTRACT contract version.
			2022-10-24T00:10:54.188Z - notify - Replication finished for DH node 4ab6cd2fb8330cea9397915ef1adaa5e4290a7a3
			2022-10-24T00:11:13.237Z - trace - Loaded replication from file for offer internal ID a5848007-8fcf-42b1-ae52-ec3c27063ad5 and color blue
			2022-10-24T00:11:13.462Z - info - Successfully sent replication data for offer_id 0x77fad6d671c54ea552aae951edc4f3ae573f8450f1a2ac055af1a927ce86b6bb to node 85b7d412ab88d04136568e7618cfeb0ce4e9c94b.
			2022-10-24T00:11:13.933Z - trace - [stargazer] Reading HOLDING_CONTRACT contract version.
			2022-10-24T00:11:13.985Z - notify - Replication finished for DH node 85b7d412ab88d04136568e7618cfeb0ce4e9c94b
			2022-10-24T00:11:27.848Z - notify - Replication window for 0x77fad6d671c54ea552aae951edc4f3ae573f8450f1a2ac055af1a927ce86b6bb is closed. Replicated to 2 peers. Verified 2.
			2022-10-24T00:11:27.849Z - error - Failed to process command dcOfferChooseCommand and ID 2453bfce-6441-4a42-8439-dac913581465. Error: Failed to choose holders. Not enough DHs submitted..
			Error: Failed to choose holders. Not enough DHs submitted.
			    at DCOfferChooseCommand.execute (/Users/cuttlefish/code/github/ot-node/modules/command/dc/dc-offer-choose-command.js:71:19)
			    at <anonymous>
			2022-10-24T00:11:27.867Z - warn - Event not sent due to releaseStage/enabledReleaseStages configuration
			2022-10-24T00:11:27.867Z - info - Deleting replications directory and cache for offer with internal ID a5848007-8fcf-42b1-ae52-ec3c27063ad5
			```

**Comment by ltfschoen** [comment]
Answering my own question:

Yes, I needed 1x DC and 3x DH nodes.

First I had to delete all the ArangoDB databases in the ArangoDB UI at http://127.0.0.1:8529/_db/_system/_admin/aardvark/index.html#databases after logging in with u: root, p: n/a; then removed /Users/cuttlefish/code/github/ot-node/tools/local-network-setup/temporary-config-files; then removed contents of folders /Users/cuttlefish/Library/ArangoDB/opt/arangodb/var/lib/arangodb3 and /Users/cuttlefish/Library/ArangoDB/opt/arangodb/var/lib/arangodb3-apps; and then finally killed the ArangoDB process id with `ps aux|grep arangod; kill -9 <PID>`; restarted ArangoDB with `/Applications/ArangoDB3-CLI.app/Contents/Resources/arangod --server.storage-engine "auto"`, then ran an extra node with `npm run tools:lns:start -- --nodes=4`

OT Client v5 output updates:
```
Replication result status: COMPLETED
{ data: 
   { gas_price_used_for_price_calculation: '20',
     holders: 
      [ '0x2fc283b9265860ab96590a0eb595a80434ed80de',
        '0x0bcacf3d4156886e26f3d9dde017e5ef6de845c7',
        '0x3931c32b900e1b2c252b9f3f8b921918e4f0dfb4' ],
     holding_time_in_minutes: 10,
     message: 'Offer has been finalized. Offer is now active.',
     number_of_replications: 3,
     number_of_verified_replications: 3,
     offer_create_transaction_hash: '0x67c620ba8ece5d3f558a7e181eee3f88f36974406cbcd1b9b03947702ddf2ec3',
     offer_finalize_transaction_hash: '0xaa6e3dd2912dd9b0446a603424c2f4029844f3dc2280b0cd5bb257243fa39166',
     offer_id: '0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2',
     price_factor_used_for_price_calculation: '3',
     status: 'FINALIZED',
     token_amount_per_holder: '120016244229744740000',
     trac_in_base_currency_used_for_price_calculation: '0.00005',
     dataset_id: '0x9389afa0dc8b3a177461b577162085acc740f627bfbdb70488041e823b8080d5' },
  status: 'COMPLETED' }
```

Logs from the OT-node v5
```
2022-10-24T01:33:21.035Z - api - POST: Replicate request received.
2022-10-24T01:33:21.065Z - trace - [stargazer] Using default trac price in base currency from configuration: 0.00005
2022-10-24T01:33:21.068Z - trace - [stargazer] Using default gas price from configuration: 20000000000
2022-10-24T01:33:21.068Z - trace - Calculated offer price for data size: 0.002111MB, and holding time: 0.006944444444444444 days, PRICE: 120016244229744740000[mTRAC]
2022-10-24T01:33:21.078Z - trace - [stargazer] Get profile by identity 0x2fa6d32e314aab43a58999d6f5532a15418da153
2022-10-24T01:33:21.114Z - trace - [stargazer] Get minimum stake from blockchain
2022-10-24T01:33:21.139Z - info - Exporting dataset: 0x9389afa0dc8b3a177461b577162085acc740f627bfbdb70488041e823b8080d5. For internal offer id: 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd.
2022-10-24T01:33:21.150Z - info - Preparing data for offer with internal id: 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd, started.
(node:57049) Warning: N-API is an experimental feature and could change at any time.
2022-10-24T01:34:14.655Z - info - Preparing data for offer with internal id: 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd, completed successfully.
2022-10-24T01:34:14.695Z - trace - [stargazer] Using default gas price from configuration: 20000000000
2022-10-24T01:34:14.695Z - trace - [stargazer] createOffer (0x2fa6d32e314aab43a58999d6f5532a15418da153, 0x9389afa0dc8b3a177461b577162085acc740f627bfbdb70488041e823b8080d5, 0x9f9c70de04049a71ef0edb819c1c588d2f938cce1d53dca174f4f9c614af24d4, 0x26f0fffc79b04bea4099e9262fd17c05b301dde7813c4568e3c016fb14a8bba3, 0x865c9e99ce6f30219d658ef6e929cccf4e231c0bffbf4ed7230901948294fff0, 0x79f84c8ec4c69c151a94c3aadce909fdf36c72dd2afe414fc56d62e80f84cf76, 0x781e64952478359bd10b79ab69d42bea189834be, 10, 120016244229744740000, 2111, 1)
2022-10-24T01:34:14.712Z - trace - Sending transaction to blockchain, nonce 60, balance is 999999999998456438980000000000
2022-10-24T01:34:14.918Z - important - Offer with internal ID 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd for data set 0x9389afa0dc8b3a177461b577162085acc740f627bfbdb70488041e823b8080d5 written to blockchain stargazer. Waiting for DHs...
2022-10-24T01:34:40.085Z - trace - Offer successfully started for data set 0x9389afa0dc8b3a177461b577162085acc740f627bfbdb70488041e823b8080d5 on blockchain stargazer. Offer ID 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2. Internal offer ID 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd.
2022-10-24T01:35:20.150Z - info - Received replication request for offer_id 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2 from node 49e206c456519e813835d99d0e1bd43767aebf66.
2022-10-24T01:35:20.159Z - info - Sending replication request acknowledgement for offer_id 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2 to node 49e206c456519e813835d99d0e1bd43767aebf66.
2022-10-24T01:35:21.700Z - info - Received replication request for offer_id 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2 from node 04bf1beece3ebf27856ebfbfdeb026dc3ddcb35a.
2022-10-24T01:35:21.712Z - info - Sending replication request acknowledgement for offer_id 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2 to node 04bf1beece3ebf27856ebfbfdeb026dc3ddcb35a.
2022-10-24T01:35:21.860Z - info - Received replication request for offer_id 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2 from node 6c02b8af8a2a3477bc2495007b990e2067562abd.
2022-10-24T01:35:21.865Z - info - Sending replication request acknowledgement for offer_id 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2 to node 6c02b8af8a2a3477bc2495007b990e2067562abd.
2022-10-24T01:35:27.640Z - trace - Loaded replication from file for offer internal ID 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd and color green
2022-10-24T01:35:27.863Z - info - Successfully sent replication data for offer_id 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2 to node 04bf1beece3ebf27856ebfbfdeb026dc3ddcb35a.
2022-10-24T01:35:27.976Z - trace - Loaded replication from cache for offer internal ID 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd and color green
2022-10-24T01:35:28.238Z - info - Successfully sent replication data for offer_id 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2 to node 6c02b8af8a2a3477bc2495007b990e2067562abd.
2022-10-24T01:35:28.307Z - trace - [stargazer] Reading HOLDING_CONTRACT contract version.
2022-10-24T01:35:28.396Z - notify - Replication finished for DH node 04bf1beece3ebf27856ebfbfdeb026dc3ddcb35a
2022-10-24T01:35:28.701Z - trace - [stargazer] Reading HOLDING_CONTRACT contract version.
2022-10-24T01:35:28.740Z - notify - Replication finished for DH node 6c02b8af8a2a3477bc2495007b990e2067562abd
2022-10-24T01:35:37.135Z - trace - Loaded replication from file for offer internal ID 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd and color blue
2022-10-24T01:35:37.372Z - info - Successfully sent replication data for offer_id 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2 to node 49e206c456519e813835d99d0e1bd43767aebf66.
2022-10-24T01:35:37.769Z - trace - [stargazer] Reading HOLDING_CONTRACT contract version.
2022-10-24T01:35:37.824Z - notify - Replication finished for DH node 49e206c456519e813835d99d0e1bd43767aebf66
2022-10-24T01:36:10.122Z - notify - Replication window for 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2 is closed. Replicated to 3 peers. Verified 3.
2022-10-24T01:36:10.123Z - trace - [stargazer] getOfferDifficulty(offer=0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2)
2022-10-24T01:36:10.159Z - important - Miner started for offer 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2.
2022-10-24T01:36:15.334Z - important - Miner found a solution of offer 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2.
2022-10-24T01:36:15.334Z - trace - [stargazer] Get minimum stake from blockchain
2022-10-24T01:36:15.366Z - trace - [stargazer] Get profile by identity 0x2fc283b9265860ab96590a0eb595a80434ed80de
2022-10-24T01:36:15.367Z - trace - [stargazer] Get profile by identity 0x0bcacf3d4156886e26f3d9dde017e5ef6de845c7
2022-10-24T01:36:15.370Z - trace - [stargazer] Get profile by identity 0x3931c32b900e1b2c252b9f3f8b921918e4f0dfb4
2022-10-24T01:36:15.440Z - trace - [stargazer] Get profile by identity 0x2fa6d32e314aab43a58999d6f5532a15418da153
2022-10-24T01:36:15.461Z - trace - [stargazer] Get minimum stake from blockchain
2022-10-24T01:36:15.507Z - trace - [stargazer] getOffer(offerId=0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2)
2022-10-24T01:36:15.532Z - trace - [stargazer] Using default gas price from configuration: 20000000000
2022-10-24T01:36:15.533Z - trace - [stargazer] finalizeOffer (0x2fa6d32e314aab43a58999d6f5532a15418da153, 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2, 31, 0x52f7eeee2b13e6c36cbf21ea2e191399ca0b42fd6a5c8cac2e4c4d8d10704db07bffa4b76615311b81026ff18902943498082b6ac19a30f2c943ccc81851f4711c, 0xdeba0b572ef9f9a6fc8426d0570eb54b22d5a8b8dc7532e2af0bb7704082d0a91b120aaadd25443449fe8095e17c72479ca20a45e9771d5f6d213601d57e9c051c, 0xccf48a3e2cba33c1f45f3e556d9707fcee5f27399aee7df5bc7f898d3454d68d0e698500aa874f7c147999bafb4317898e8df8fd48e9353f0b36be3d1fd5b2f61b, 1,2,1, 0x2fc283b9265860ab96590a0eb595a80434ed80de,0x0bcacf3d4156886e26f3d9dde017e5ef6de845c7,0x3931c32b900e1b2c252b9f3f8b921918e4f0dfb4), 0
2022-10-24T01:36:15.547Z - trace - Sending transaction to blockchain, nonce 61, balance is 999999999998450096480000000000
2022-10-24T01:36:21.057Z - important - Offer 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2 finalized on blockchain stargazer
2022-10-24T01:36:21.088Z - trace - Loaded replication from cache for offer internal ID 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd and color green
2022-10-24T01:36:21.095Z - trace - Loaded replication from cache for offer internal ID 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd and color blue
2022-10-24T01:36:21.101Z - trace - Loaded replication from cache for offer internal ID 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd and color green
2022-10-24T01:36:21.117Z - info - Deleting replications directory and cache for offer with internal ID 4dda28f7-8081-481f-bcd3-fbfb5f9f0edd
2022-10-24T01:37:12.804Z - trace - Sending challenge to 04bf1beece3ebf27856ebfbfdeb026dc3ddcb35a. Offer ID 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2, object_index 0, block_index 5.
2022-10-24T01:37:12.885Z - info - Challenge response arrived for challenge 43d40861-e333-47fd-8185-4c51ccec2d04. Answer +5OCwsFJo/4YqpY3Lcy3hF2BIC/XAQo
2022-10-24T01:40:38.989Z - trace - Sending challenge to 49e206c456519e813835d99d0e1bd43767aebf66. Offer ID 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2, object_index 0, block_index 6.
2022-10-24T01:40:39.179Z - info - Challenge response arrived for challenge 586c3e05-c97f-4f4f-b89f-a6026db4e841. Answer VDKkFXp8qrX6Wui/h2Bo9VidnD8MP5A
2022-10-24T01:41:09.403Z - trace - Sending challenge to 6c02b8af8a2a3477bc2495007b990e2067562abd. Offer ID 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2, object_index 0, block_index 14.
2022-10-24T01:41:09.503Z - info - Challenge response arrived for challenge df4878d5-c6fa-4141-ace1-f9942f7d7224. Answer d69RjdN8yiA==","relations":[]}0
2022-10-24T01:42:12.897Z - trace - Holder 0x2fc283b9265860ab96590a0eb595a80434ed80de successfully answered to challenge for offer 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2.
2022-10-24T01:42:14.928Z - trace - Sending challenge to 04bf1beece3ebf27856ebfbfdeb026dc3ddcb35a. Offer ID 0x7e4d72ecf6f99012e64605f40b7ac26c62cf410f11c1a5917f43281444b2dcd2, object_index 0, block_index 13.
2022-10-24T01:42:15.003Z - info - Challenge response arrived for challenge a0a3a871-3a1f-46fe-a2a2-3d15e9aa5835. Answer Xd+8QEvQJswEdFZcNMYDTbc0jKNqQU3
```
